# Generated by Django 3.0.4 on 2020-05-31 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('made_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('school_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentQuestionRel',
            fields=[
                ('as_qurel_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MakeQuestion',
            fields=[
                ('make_question_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('hint', models.TextField()),
                ('made_date', models.DateField()),
                ('upload_check', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=50)),
                ('question_name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('hint', models.TextField()),
                ('made_date', models.DateField()),
                ('qr_code', models.CharField(max_length=100)),
                ('ques_concept', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('approve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudySolveData',
            fields=[
                ('study_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('response', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submit_date', models.DateField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('solve_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('submit_date', models.DateField()),
                ('response', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_name', models.CharField(max_length=50)),
                ('as_qurel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.AssignmentQuestionRel')),
            ],
        ),
        migrations.CreateModel(
            name='SelfSolveData',
            fields=[
                ('self_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submit_date', models.DateField()),
                ('make_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.MakeQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mark_text', models.TextField()),
                ('make_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.MakeQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='makequestion',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Teacher'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Question')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentquestionrel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Question'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.Teacher'),
        ),
    ]
