# Generated by Django 3.0.6 on 2020-06-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200617_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='student_name',
        ),
    ]
