# Generated by Django 3.0.6 on 2020-06-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_solve_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='question/image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qr_code',
            field=models.ImageField(upload_to='qr_code/image'),
        ),
    ]
