# Generated by Django 3.0.4 on 2020-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200505_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mark_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mark',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CategoryQuestionRel',
        ),
    ]
